# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 #checkout 代码
        
      - name: Get current day
        id: day
        run: echo "::set-output name=day::$(date +'%Y%m%d')"
        
      - name: Get current minute
        id: minute
        run: echo "::set-output name=minute::$(date +'%H%m')"

      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: nightly-tag-${{ steps.day.outputs.day }}
          RELEASE_NAME: nightly-release-${{ steps.minute.outputs.minute }}
          
      - uses: yukiarrr/ios-build-action@v1.4.0
        with:
            project-path: Actions.xcodeproj
#            workspace-path: ActionsTest.xcworkspace # optional
            p12-key-base64: ${{ secrets.P12_KEY_BASE64 }}
            p12-cer-base64: ${{ secrets.P12_CER_BASE64 }}
            mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
            code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
            team-id: ${{ secrets.TEAM_ID }}
            export-method: 'development'
            certificate-password: ${{ secrets.CERTIFICATE_PASSWORD }}
            output-path: ${{ steps.day.outputs.day }}/${{ steps.minute.outputs.minute }}.ipa
#            output-path: ${{ github.run_id }}.ipa

            
      - name: push to fir
        run: curl -F $PATH -F '_api_key=ae0aac62cabfbd64173ee7af786d051d' https://www.pgyer.com/apiv2/app/upload
        env:
          PATH: file=@/Users/jiwenzhang/actions-runner/_work/Actions/Actions/${{ steps.day.outputs.day }}/${{ steps.minute.outputs.minute }}.ipa

            
