# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 #checkout 代码
        
#      - name: Run a one-line script
#        run: echo Hello, world!

#      - shell: bash
#        run: |
#          expr 25.ipa > name_number.log

      - run: path = 3021.ipa
          
      - uses: yukiarrr/ios-build-action@v1.4.0
        with:
            project-path: Actions.xcodeproj
#            workspace-path: ActionsTest.xcworkspace # optional
            p12-key-base64: ${{ secrets.P12_KEY_BASE64 }}
            p12-cer-base64: ${{ secrets.P12_CER_BASE64 }}
            mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
            code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
            team-id: ${{ secrets.TEAM_ID }}
            export-method: 'development'
            certificate-password: ${{ secrets.CERTIFICATE_PASSWORD }}
            output-path: path
            
      - name: push to fir
        run: curl -F 'file=@/Users/jiwenzhang/actions-runner/_work/Actions/Actions/output.ipa' -F '_api_key=ae0aac62cabfbd64173ee7af786d051d' https://www.pgyer.com/apiv2/app/upload

            
