# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 #checkout 代码
        
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%m%d%H%m')"
        
#      - name: Get current minute
#        id: minute
#        run: echo "::set-output name=minute::$(date +'%H%m')"

#      - name: Test with environment variables
#        run: echo $TAG_NAME #- $RELEASE_NAME
#        env:
#          TAG_NAME: nightly-tag-${{ steps.date.outputs.date }}
#          RELEASE_NAME: nightly-release-${{ steps.minute.outputs.minute }}
          
      - uses: yukiarrr/ios-build-action@v1.4.0
        with:
            project-path: Actions.xcodeproj
#            workspace-path: ActionsTest.xcworkspace # optional
            p12-key-base64: ${{ secrets.P12_KEY_BASE64 }}
            p12-cer-base64: ${{ secrets.P12_CER_BASE64 }}
            mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
            code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
            team-id: ${{ secrets.TEAM_ID }}
            export-method: 'development'
            certificate-password: ${{ secrets.CERTIFICATE_PASSWORD }}
            output-path: /Users/jiwenzhang/Desktop/${{ steps.date.outputs.date }}/${{ github.run_number }}/me.ipa
#            output-path: /Users/jiwenzhang/Desktop/${{ steps.date.outputs.date }}/me.ipa
#            output-path: output.ipa
#            output-path: ${{ github.run_id }}.ipa

      - name: push to fir
        id: PushToFir
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://www.pgyer.com/apiv2/app/upload'
          method: 'POST'
          data: ${{ toJSON({_api_key:'ae0aac62cabfbd64173ee7af786d051d',file: @/Users/jiwenzhang/Desktop/${{ steps.date.outputs.date }}/${{ github.run_number }}/me.ipa}) }}
#          data: {_api_key:'ae0aac62cabfbd64173ee7af786d051d',file: @/Users/jiwenzhang/Desktop/${{ steps.date.outputs.date }}/${{ github.run_number }}/me.ipa}
            
      - name: Show Response
        run: echo ${{ steps.PushToFir.outputs.response }}



#      - name: push to fir
#        run: curl -F file=@/Users/jiwenzhang/Desktop/${{ steps.date.outputs.date }}/${{ github.run_number }}/me.ipa -F '_api_key=ae0aac62cabfbd64173ee7af786d051d' https://www.pgyer.com/apiv2/app/upload



#      - name: push to fir
#        run: curl -F file=@/Users/jiwenzhang/Desktop/${{ steps.date.outputs.date }}/me.ipa -F '_api_key=ae0aac62cabfbd64173ee7af786d051d' https://www.pgyer.com/apiv2/app/upload

#      - name: push to fir
#        run: curl -F file=@/Users/jiwenzhang/actions-runner/_work/Actions/Actions/${{ steps.date.outputs.date }}/me.ipa -F '_api_key=ae0aac62cabfbd64173ee7af786d051d' https://www.pgyer.com/apiv2/app/upload

            
